# ==========================================
# MASTER REALM LIST (EU) - COMPLETE & GROUPED
# Data Source: Mega Alerts / Blizzard API
# ==========================================
REALMS = {
    "Khadgar/Bloodhoof": 1080,
    "Tarren Mill/Dentarg": 1084,
    "Karazhan/Dragonblight/The Maelstrom/Ghostlands/Lightning's Blade/Deathwing": 1596,
    "Auchindoun/Dunemaul/Sylvanas/Jaedenar": 1597,
    "Shattered Halls/Chromaggus/Sunstrider/Balnazzar/Talnivarr/Ahn'Qiraj/Daggerspine/Laughing Skull/Trollbane/Boulderfist": 1598,
    "Gordunni": 1602,
    "Soulflayer": 1604,
    "Deathguard": 1605,
    "Galakrond/Deepholm/Razuvious": 1614,
    "Thrall/Kargath/Ambossar": 604,
    "Emeriss/Twilight's Hammer/Bloodscalp/Crushridge/Agamaggan/Hakkar": 1091,
    "Drak'thul/Burning Blade": 1092,
    "Ysera/Malorne": 1097,
    "Malygos/Malfurion": 1098,
    "Anetheron/Kil'jaeden/Rajaxx/Festung der Sturme/Gul'dan/Nathrezim": 1104,
    "Nazjatar/Zuluhed/Dalvengyr/Aman'Thul/Frostmourne/Anub'arak": 1105,
    "Die Arguswacht/Die ewige Wacht/Die Todeskrallen/Das Syndikat/Der abyssische Rat/Kult der Verdammten/Das Konsortium/Die Silberne Hand": 1121,
    "Uldaman/Drek'Thar/Krasus/Eitrigg": 1122,
    "Confrerie du Thorium/La Croisade ecarlate/Culte de la Rive noire/Les Sentinelles/Kirin Tor/Les Clairvoyants/Conseil des Ombres": 1127,
    "Turalyon/Doomhammer": 1402,
    "Blade's Edge/Eonar/Vek'nilash/Aerie Peak/Bronzebeard": 1416,
    "Dethecus/Theradras/Onyxia/Mug'thol/Terrordar": 531,
    "Vol'jin/Chants eternels": 510,
    "Arak-arahm/Rashgarroth/Kael'thas/Throk'Feroth": 512,
    "Nefarian/Gilneas/Destromath/Ulduar/Mannoroth/Gorgonnash/Nera'thor": 612,
    "Kor'gall/Executus/Shattered Hand/Bloodfeather/Terokkar/Saurfang/Darkspear/Burning Steppes": 633,
    "Suramar/Medivh": 1331,
    "Garrosh/Shattrath/Nozdormu/Perenolde/Teldrassil": 1401,
    "Draenor": 1403,
    "Arygos/Khaz'goroth": 1406,
    "Marecage de Zangar/Cho'gall/Eldre'Thalas/Sinstralis/Dalaran": 1621,
    "Naxxramas/Arathi/Illidan/Temple noir": 1624,
    "Arthas/Blutkessel/Wrathbringer/Durotan/Kel'Thuzad/Vek'lor/Tirion": 578,
    "Blackmoore/Tichondrius/Lordaeron": 580,
    "Howling Fjord": 1615,
    "Chamber of Aspects": 1307,
    "Pozzo dell'Eternita": 1309,
    "Blackrock": 581,
    "Garona/Sargeras/Ner'zhul": 509,
    "Aggramar/Hellscream": 1325,
    "Ravencrest": 1329,
    "Ysondre": 1335,
    "Wildhammer/Thunderhorn": 1313,
    "Nemesis": 1316,
    "Fordragon": 1623,
    "Lothar/Baelgun/Azshara/Krag'jin": 570,
    "Scarshield Legion/Sporeggar/Earthen Ring/Defias Brotherhood/Ravenholdt/Darkmoon Faire/The Venture Co": 1096,
    "Kul Tiras/Alonsus/Anachronos": 1082,
    "Dun Modr/C'Thun": 1378,
    "Zul'jin/Uldum/Sanguino/Shen'dralar": 1379,
    "Tyrande/Los Errantes/Colinas Pardas": 1384,
    "Exodar/Minahonda": 1385,
    "Lightbringer/Mazrigos": 1388,
    "Bronze Dragonflight/Nordrassil": 1393,
    "Quel'Thalas/Azjol-Nerub": 1396,
    "Un'Goro/Sen'jin/Area 52": 1400,
    "Rexxar/Alleria": 1099,
    "Die Aldor": 1618,
    "Hyjal": 1390,
    "Eversong": 1925,
    "Goldrinn/Lich King/Greymane": 1928,
    "Blackscar/Deathweaver/Borean Tundra/Thermaplugg/Grom/Booty Bay": 1929,
    "Todeswache/Zirkel des Cenarius/Der Mithrilorden/Forscherliga/Der Rat von Dalaran/Die Nachtwache": 1405,
    "Azuremyst/Stormrage": 1417,
    "Stormscale": 2073,
    "Terenas/Emerald Dream": 2074,
    "Archimonde": 1302,
    "Grim Batol/Aggra (Portuguus)/Frostmane": 1303,
    "Kazzak": 1305,
    "Moonglade/Steamwheedle Cartel/The Sha'tar": 1085,
    "Elune/Varimathras": 1315,
    "Hellfire/Runetotem/Arathor/Kilrogg/Nagrand": 1587,
    "Outland": 1301,
    "Azuregos": 1922,
    "Ashenvale": 1923,
    "Norgannon/Dun Morogh": 1408,
    "Silvermoon": 3391,
    "Spinebreaker/Dragonmaw/Vashj/Stormreaver/Haomarush": 3656,
    "Genjuros/Zenedar/Bladefist/Neptulon/Frostwhisper/Darksorrow": 3657,
    "Shadowsong/Aszune": 3666,
    "Argent Dawn": 3702,
    "Frostwolf": 3703,
    "Al'Akir/Skullcrusher/Xavius/Burning Legion": 3713,
    "Twisting Nether": 3674,
    "Aegwynn": 3679,
    "Magtheridon": 3681,
    "Ragnaros": 3682,
    "Antonidas": 3686,
    "Khaz Modan": 3690,
    "Echsenkessel/Blackhand/Mal'Ganis/Taerar": 3691,
    "Eredar": 3692,
    "Nethersturm/Alexstrasza/Madmortem/Proudmoore": 3696
}