# realms_na.py

# ==========================================
# MASTER REALM LIST (NA)
# Data Source: Saddlebag / Blizzard API
# ==========================================
REALMS = {
    "Kilrogg/Winterhoof": 4,
    "Proudmoore": 5,
    "Kil'jaeden": 9,
    "Tichondrius": 11,
    "Silver Hand/Thorium Brotherhood/Farstriders": 12,
    "Eitrigg/Shu'halo": 47,
    "Alleria/Exodar/Medivh/Khadgar": 52,
    "Hellscream/Gorefiend/Spinebreaker/Zangarmarsh/Wildhammer/Eredar": 53,
    "Blackhand/Galakrond": 54,
    "Whisperwind/Dentarg": 55,
    "Illidan": 57,
    "Stormreaver": 58,
    "Stormrage": 60,
    "Zul'jin": 61,
    "Durotan/Ysera": 63,
    "Bloodhoof/Duskwood": 64,
    "Elune/Laughing Skull/Auchindoun/Cho'gall/Gilneas": 67,
    "Arthas": 69,
    "Warsong/Gorgonnash/The Forgotten Coast/Balnazzar/Alterac Mountains/Undermine/Anvilmar": 71,
    "Bleeding Hollow": 73,
    "Argent Dawn/The Scryers": 75,
    "Sargeras": 76,
    "Azgalor/Thunderlord/Destromath/Blood Furnace/Mannoroth/Nazjatar/Azshara": 77,
    "Magtheridon/Anetheron/Ysondre/Altar of Storms": 78,
    "Dragonmaw/Uldum/Akama/Korialstrasz/Eldre'Thalas/Mug'thol/Antonidas": 84,
    "Silvermoon/Skywall/Terenas/Hydraxis/Drak'thul/Borean Tundra/Mok'Nathal/Shadowsong": 86,
    "Eonar/Skullcrusher/Gul'dan/Zuluhed/Ursin/Andorhal/Black Dragonflight/Velen/Scilla": 96,
    "Llane/Arygos": 99,
    "Earthen Ring": 100,
    "Malygos/Garona/Lightning's Blade/Icecrown/Onyxia/Burning Blade": 104,
    "Aggramar/Fizzcrank": 106,
    "Suramar/Windrunner/Darrowmere/Draka": 113,
    "Dragonblight/Fenris": 114,
    "Draenor/Echo Isles": 115,
    "Bronzebeard/Shandris": 117,
    "Feathermoon/Scarlet Crusade": 118,
    "Darkspear": 120,
    "Azjol-Nerub/Muradin/Nordrassil/Blackrock/Khaz Modan": 121,
    "Shadow Council/Sisters of Elune/Cenarion Circle/Blackwater Raiders": 125,
    "Firetree/Drak'Tharon/Rivendare/Vashj/Spirestone/Malorne/Frostwolf/Stormscale": 127,
    "Runetotem/Uther": 151,
    "Detheroc/Dethecus/Lethon/Blackwing Lair/Shadowmoon/Haomarush": 154,
    "Kalecgos/Shattered Halls/Executus/Deathwing": 155,
    "Dark Iron/Shattered Hand/Coilfang/Demon Soul/Dalvengyr": 157,
    "Greymane/Tanaris": 158,
    "Staghelm/Dawnbringer/Madoran/Azuremyst": 160,
    "Emerald Dream": 162,
    "Maelstrom/Twisting Nether/Lightninghoof/The Venture Co/Ravenholdt": 163,
    "Alexstrasza/Terokkar": 1070,
    "Kirin Tor/Steamwheedle Cartel/Sentinels": 1071,
    "Ravencrest/Uldaman": 1072,
    "Agamaggan/Kargath/Burning Legion/Thunderhorn/The Underbog/Blade's Edge/Archimonde/Norgannon/Jaedenar": 1129,
    "Aegwynn/Gurubashi/Bonechewer/Hakkar/Garrosh/Daggerspine": 1136,
    "Chromaggus/Nathrezim/Smolderthorn/Anub'arak/Arathor/Garithos/Drenden/Crushridge": 1138,
    "Kul Tiras/Bladefist": 1147,
    "Rexxar/Misha": 1151,
    "Cairne/Cenarius/Frostmane/Tortheldrin/Ner'zhul/Korgath/Perenolde": 1168,
    "Wyrmrest Accord": 1171,
    "Trollbane/Grizzly Hills/Malfurion/Lothar/Kael'thas/Gnomeregan/Moonrunner/Ghostlands": 1175,
    "Vek'nilash/Nazgrel/Nesingwary": 1184,
    "Sen'jin/Dunemaul/Maiev/Bloodscalp/Quel'dorei/Boulderfist/Stonemaul": 1185,
    "Baelgun/Doomhammer": 1190,
    "Drakkari": 1425,
    "Aerie Peak": 1426,
    "Ragnaros": 1427,
    "Quel'Thalas": 1428,
    "Goldrinn": 3207,
    "Nemesis/Tol Barad": 3208,
    "Azralon": 3209,
    "Gallywix": 3234,
    "Hyjal": 3661,
    "Moon Guard": 3675,
    "Area 52": 3676,
    "Thrall": 3678,
    "Dalaran": 3683,
    "Mal'Ganis": 3684,
    "Turalyon": 3685,
    "Kel'Thuzad": 3693,
    "Lightbringer": 3694,
    "Caelestrasz/Nagrand/Saurfang": 3721,
    "Barthilas": 3723,
    "Frostmourne/Dreadmaul/Thaurissan/Jubei'Thos/Gundrak": 3725,
    "Khaz'goroth/Aman'Thul/Dath'Remar": 3726,
}
